name: Java CI with Maven

on:

  workflow_dispatch:

    inputs:
    Browser:
        type: choice
        description: 'Browser'
        required: true
        default: 'chrome-headless'
        options: 
        - chrome
        - firefox
        - chrome-sm
        - chrome-headless

jobs:

  test:
    
    runs-on: ${{ github.event.inputs.Browser == 'chrome-headless' ? 'ubuntu-latest':'macos-latest' }}


    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 11

      uses: actions/setup-java@v3

      with:

        java-version: '11'

        distribution: 'temurin'

        cache: maven
    - name: Check if Chrome is installed
      run: google-chrome --version

    - name: Check Chrome binary path
      run: which google-chrome
      
    - name: Change permissions for Chrome binary
      run: sudo chmod +x /usr/bin/google-chrome
      
    #- name: Set WebDriverManager Path 
     # run: |
      #    echo "webdrivermanager.chromedriver.binary.path=/src/main" >> $GITHUB_ENV

    #- name: Install WebDriverManager
     # run: yarn add webdriver-manager

    - name: Build with Maven

      run: mvn clean test


