name: Java CI with Maven

on:

  workflow_dispatch:

   inputs:
    Browser:
        type: choice
        description: 'Browser'
        required: true
        default: 'chrome-headless'
        options: 
        - chrome
        - firefox
        - chrome-sm
        - chrome-headless

jobs:
  test:
    runs-on: |
      if [ "${{ github.event.inputs.TestType }}" == "chrome-headless" ]; then
       ubuntu-latest
      else 
       macos-latest
      fi
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11

      uses: actions/setup-java@v3

      with:

        java-version: '11'

        distribution: 'temurin'

        cache: maven
    - name: Print OS details
      run: |
        echo "OS Name: ${{ runner.os }}"

    - name: Build with Maven

      run: mvn clean test


