name: Java CI with Maven

on:

  workflow_dispatch:

    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 11

      uses: actions/setup-java@v3

      with:

        java-version: '11'

        distribution: 'temurin'

        cache: maven
    - name: Check if Chrome is installed
      run: google-chrome --version

    - name: Check Chrome binary path
      run: which google-chrome
    - name: Change permissions for Chrome binary
      run: sudo chmod +x /path/to/google-chrome
    #- name: Set WebDriverManager Path 
     # run: |
      #    echo "webdrivermanager.chromedriver.binary.path=/src/main" >> $GITHUB_ENV

    #- name: Install WebDriverManager
     # run: yarn add webdriver-manager

    - name: Build with Maven

      run: mvn clean test


